# Linear Algebra
### 1. Scalers & Vectors

* **Scalars** is a single number denoted by $x$.
* **Vector** is an array of scalers, denoted by $x$.
     * Thus, a vector has n scalers $x_1$,$x_2$,$x_3$....$x_n$.
     * Note that the indexing here begins with 1, unlike python.(where it begins with zero)
\begin{equation}
x = 
\begin{bmatrix}
x_1 \\
x_2 \\
... \\
x_n \\
\end{bmatrix}
\end{equation}

In [1]:
import numpy as np

In [2]:
x=np.array([4,5,6])
print(x)
print(x.shape)
print(x[0])

[4 5 6]
(3,)
4


In [3]:
x=np.array([[4],[5],[6]])
print(x)
print(x.shape)
print(x[0][0])

[[4]
 [5]
 [6]]
(3, 1)
4


In [4]:
x=x.reshape((-1,))
print(x)
print(x.shape)

[4 5 6]
(3,)


### 2. Matrices and Tensors
* **Matrix** is a 2D array of scalers, denoted by $X$.
\begin{equation}
X = 
\begin{bmatrix}
X_1,_1&X_1,_2&...&X_1,_n\\
X_2,_1&X_2,_2&...&X_2,_n\\
...&...&...&...\\
X_m,_1&X_m,_2&...&X_m,_n\\
\end{bmatrix}
\end{equation}
    * This matrix has $m$ rows and $n$ columns.
    * Each individual element such as $X_1,_1$ is a scalar.
    * If $m=n$, the matrix is known as **Square** matrix.

* **Tensor** is an array with more than two axes, denoted as $X$

In [5]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)

(3, 3)


In [6]:
t=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)
print(t.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


### 3. Transpose
* For a 2D matrix, transpose can be obtained as follow $(A^T)_{ij})$=$A_{ji}$
* For a vector, transpose makes the column vector into row. Thus a column vector can also be represented as $x=[x_1,x_2,x_3]^T$

In [7]:
x_t=np.transpose(x)
print(x_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
x=x.reshape((-1,1))
print(x.shape)
x_t=np.transpose(x)
print(x_t)
print(x_t.shape)

(9, 1)
[[1 2 3 4 5 6 7 8 9]]
(1, 9)


### 4. Broadcasting
You can add a scaler to a vector, and numpy will add it to each element in the vector.

$(x+a=x_i+a)$

Similarly we can add a vector to a matrix, and numpy will add the vector to each column of the matrix.


In [9]:
x=np.array([1,2,3,4])
x=x+5
print(x)

[6 7 8 9]


In [10]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=x**2
print(x)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 5. Matrix Multiplication
* A useful method to think of Matrix multiplication is as linear combination of columns of $A$ weighted by column entries of $B$

In [11]:
x=np.array([[1,1,1],[1,1,1],[1,1,1]])
y=np.array([[3,3,3],[3,3,3],[3,3,3]])

print(np.dot(x,y))

[[9 9 9]
 [9 9 9]
 [9 9 9]]


### 6. Element Wise multiplication: Hadamard Product

In [12]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.eye(3)
print(x*y)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


### 7. Norms
* Norm can be thought of as a proxy for size of a vector.

In [13]:
x=np.array([-5,3,10])
print(np.linalg.norm(x,ord=2))
print(np.linalg.norm(x,ord=1))
print(np.linalg.norm(x,ord=np.inf))

11.575836902790225
18.0
10.0
