# Numpy Arrays

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
a=np.array([[1],[2],[3],[4],[5]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [4]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


### Numpy array of zeros, ones, identity, constant, random

In [5]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
a=np.full((3,3),5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [8]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a=np.random.random((3,3))
print(a)

[[0.44360417 0.3503578  0.60655634]
 [0.57817126 0.94922443 0.72393922]
 [0.74876966 0.81777854 0.68308399]]


In [10]:
print(a[:,1])
print(a[:2,2])
a[:,:]=1
print(a)

[0.3503578  0.94922443 0.81777854]
[0.60655634 0.72393922]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
a=np.zeros((3,3),dtype=np.int64)
print(a)
a[0,2]=5
a[1,:]=5
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 5]
 [5 5 5]
 [0 0 0]]


In [12]:
print(a.dtype)

int64


### Mathematical Operations

* Element-wise addition, subtraction, multiplication, division.
* Dot Product

In [13]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [14]:
print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
print(a.dot(b))
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [16]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a.dot(b))
print(np.dot(a,b))

70
70


In [17]:
a=np.array([[5,6],[7,8]])
print(sum(a))
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[12 14]
26
[12 14]
[11 15]


### Stacking of arrays

In [18]:
a=np.array([1,2,3,4])
b=a**2
print(a)
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [19]:
c=np.stack((a,b),axis=1)
print(c)
c=np.stack((a,b),axis=0)
print(c)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]


### Reshaping of arrays

In [20]:
print(c)
c=c.reshape((4,2))
print(c)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [21]:
print(c.reshape((8,1)))
print(c.reshape((8,)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]
[ 1  2  3  4  1  4  9 16]


In [22]:
print(c.reshape((8,-1)))
print(c.reshape((2,-1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]
