## Numpy Random Module
* **rand** : Random values in a given shape.
* **randn** : Return a sample (or samples) from the "standard normal" ditribution.
* **randint** : Return random integers from low(inclusive) to high(exclusive)
* **random** : Return random floats in the half-open interval [0.0, 1.0)
* **choice** : Generates a random sample from a given 1D array.
* **Shuffle** : Shuffles the contents of the sequence.

In [1]:
import numpy as np

In [2]:
a=np.arange(10)
print(a)
print(a+5)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [3]:
a=np.random.rand(2,3)
print(a)

[[0.34673042 0.48167591 0.66464977]
 [0.37294195 0.10157565 0.67964585]]


In [4]:
a=np.random.randn(2,3)
print(a)

[[ 1.56204649 -1.42888653  0.00770563]
 [-0.20401201 -0.12850177 -1.3716335 ]]


In [5]:
a=np.random.randint(5,10,3)
print(a)

[7 5 8]


In [6]:
a=np.random.random(5)
print(a)

[0.04302506 0.02543294 0.26820277 0.01129126 0.65275305]


In [7]:
a=np.random.choice([1,2,3,4,5])
print(a)

5


In [8]:
a=np.arange(10)
np.random.seed(2)
np.random.shuffle(a)
print(a)

[4 1 5 0 7 2 3 6 9 8]
